// <auto-generated />
using GeekShopping.ProductAPI.Model.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeekShopping.ProductAPI.Migrations
{
    [DbContext(typeof(MySQLContext))]
    [Migration("20241212160533_SeedProductDataTable")]
    partial class SeedProductDataTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("GeekShopping.ProductAPI.Model.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("category_name");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("name");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)")
                        .HasColumnName("price");

                    b.HasKey("Id");

                    b.ToTable("product");

                    b.HasData(
                        new
                        {
                            Id = 2L,
                            CategoryName = "T-Shirt",
                            Description = "Camiseta no Internet",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/2_no_internet.jpg",
                            Name = "No Internet",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 3L,
                            CategoryName = "Toy",
                            Description = "Capacete Vade",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/3_vader.jpg",
                            Name = "Vader",
                            Price = 79.9m
                        },
                        new
                        {
                            Id = 4L,
                            CategoryName = "Toy",
                            Description = "Boneco Storm Tropper",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/4_storm_tropper.jpg",
                            Name = "Storm Tropper",
                            Price = 89.9m
                        },
                        new
                        {
                            Id = 5L,
                            CategoryName = "T-Shirt",
                            Description = "Camiseta 100 Gamer",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/5_100_gamer.jpg",
                            Name = "100 Gamer",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 6L,
                            CategoryName = "T-Shirt",
                            Description = "Camiseta Space X",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/6_spacex.jpg",
                            Name = "Space X",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 7L,
                            CategoryName = "T-Shirt",
                            Description = "Camiseta Coffe",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/7_coffee.jpg",
                            Name = "Coffe",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 8L,
                            CategoryName = "Blusa",
                            Description = "Moletom Cobra Kay",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/8_moletom_cobra_kay.jpg",
                            Name = "Cobra Kay",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 9L,
                            CategoryName = "Book",
                            Description = "Neil",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/9_neil.jpg",
                            Name = "Neil",
                            Price = 109.9m
                        },
                        new
                        {
                            Id = 10L,
                            CategoryName = "Toy",
                            Description = "Milennium Falcon",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/10_milennium_falcon.jpg",
                            Name = "Milennium Falcon",
                            Price = 109.9m
                        },
                        new
                        {
                            Id = 11L,
                            CategoryName = "T-Shirt",
                            Description = "Occupy Mars",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/11_mars.jpg",
                            Name = "Mars",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 12L,
                            CategoryName = "T-Shirt",
                            Description = "Gnu Linux Freedom",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/12_gnu_linux.jpg",
                            Name = "Gnu Linux",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 13L,
                            CategoryName = "T-Shirt",
                            Description = "Dragon Ball",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/13_dragon_ball.jpg",
                            Name = "Dragon Ball",
                            Price = 69.9m
                        },
                        new
                        {
                            Id = 14L,
                            CategoryName = "T-Shirt",
                            Description = "Patch Nasa",
                            ImageURL = "https://github.com/ViniciusOrram/Microservice-dotnet6/blob/main/ShoppingImages/14_patch_nasa.jpg",
                            Name = "Nasa",
                            Price = 69.9m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
